const statesMockResponse = [
  {"id": 3627, "value": "Alabama"},
  {"id": 3860, "value": "Alaska"},
  {"id": 4276, "value": "Arizona"},
  {"id": 4464, "value": "Arkansas"},
  {"id": 4644, "value": "California"},
  {"id": 4985, "value": "Colorado"},
  {"id": 5146, "value": "Connecticut"},
  {"id": 5299, "value": "Delaware"},
  {"id": 5449, "value": "District of Columbia"},
  {"id": 5585, "value": "Florida"},
  {"id": 5709, "value": "Georgia"},
  {"id": 5905, "value": "Hawaii"},
  {"id": 5988, "value": "Idaho"},
  {"id": 6065, "value": "Illinois"},
  {"id": 6132, "value": "Indiana"},
  {"id": 6191, "value": "Iowa"},
  {"id": 6234, "value": "Kansas"},
  {"id": 6262, "value": "Kentucky"},
  {"id": 6283, "value": "Louisiana"},
  {"id": 6305, "value": "Maine"},
  {"id": 6322, "value": "Maryland"},
  {"id": 6334, "value": "Massachusetts"},
  {"id": 6345, "value": "Michigan"},
  {"id": 6357, "value": "Minnesota"},
  {"id": 6369, "value": "Mississippi"},
  {"id": 6382, "value": "Missouri"},
  {"id": 6394, "value": "Montana"},
  {"id": 6405, "value": "Nebraska"},
  {"id": 6416, "value": "Nevada"},
  {"id": 6423, "value": "New Hampshire"},
  {"id": 6429, "value": "New Jersey"},
  {"id": 6435, "value": "New Mexico"},
  {"id": 6441, "value": "New York"},
  {"id": 6447, "value": "North Carolina"},
  {"id": 6453, "value": "North Dakota"},
  {"id": 6459, "value": "Ohio"},
  {"id": 6465, "value": "Oklahoma"},
  {"id": 6471, "value": "Oregon"},
  {"id": 6477, "value": "Pennsylvania"},
  {"id": 6488, "value": "Rhode Island"},
  {"id": 6494, "value": "South Carolina"},
  {"id": 6500, "value": "South Dakota"},
  {"id": 6506, "value": "Tennessee"},
  {"id": 6512, "value": "Texas"},
  {"id": 6518, "value": "Utah"},
  {"id": 6524, "value": "Vermont"},
  {"id": 6529, "value": "Virginia"},
  {"id": 6536, "value": "Washington"},
  {"id": 6538, "value": "West Virginia"},
  {"id": 6540, "value": "Wisconsin"},
  {"id": 6542, "value": "Wyoming"}
];

const countryMockResponse = [
  {"id": 4, "value": "Afghanistan"},
  {"id": 247, "value": "Åland Islands"},
  {"id": 7, "value": "Albania"},
  {"id": 5, "value": "Algeria"},
  {"id": 11, "value": "American Samoa"},
  {"id": 9, "value": "Andorra"},
  {"id": 10, "value": "Angola"},
  {"id": 15, "value": "Anguilla"},
  {"id": 16, "value": "Antarctica"},
  {"id": 2, "value": "Antigua and Barbuda"},
  {"id": 12, "value": "Argentina"},
  {"id": 8, "value": "Armenia"},
  {"id": 1, "value": "Aruba"},
  {"id": 13, "value": "Australia"},
  {"id": 14, "value": "Austria"},
  {"id": 6, "value": "Azerbaijan"},
  {"id": 22, "value": "Bahamas"},
  {"id": 17, "value": "Bahrain"},
  {"id": 23, "value": "Bangladesh"},
  {"id": 18, "value": "Barbados"},
  {"id": 28, "value": "Belarus"},
  {"id": 21, "value": "Belgium"},
  {"id": 24, "value": "Belize"},
  {"id": 27, "value": "Benin"},
  {"id": 20, "value": "Bermuda"},
  {"id": 31, "value": "Bhutan"},
  {"id": 26, "value": "Bolivia"},
  {"id": 163, "value": "Bonaire, St Eustatius, Saba"},
  {"id": 25, "value": "Bosnia & Herzegovina"},
  {"id": 19, "value": "Botswana"},
  {"id": 33, "value": "Bouvet Island"},
  {"id": 30, "value": "Brazil"},
  {"id": 104, "value": "British Indian Ocean"},
  {"id": 34, "value": "Brunei"},
  {"id": 32, "value": "Bulgaria"},
  {"id": 224, "value": "Burkina Faso"},
  {"id": 35, "value": "Burundi"},
  {"id": 37, "value": "Cambodia"},
  {"id": 46, "value": "Cameroon"},
  {"id": 36, "value": "Canada"},
  {"id": 53, "value": "Cape Verde"},
  {"id": 44, "value": "Cayman Islands"},
  {"id": 51, "value": "Central African Rep."},
  {"id": 38, "value": "Chad"},
  {"id": 43, "value": "Chile"},
  {"id": 42, "value": "China"},
  {"id": 119, "value": "Christmas Island"},
  {"id": 45, "value": "Cocos (Keeling) Is."},
  {"id": 48, "value": "Colombia"},
  {"id": 47, "value": "Comoros"},
  {"id": 41, "value": "Congo, Dem. Rep"},
  {"id": 40, "value": "Congo, Republic"},
  {"id": 54, "value": "Cook Islands"},
  {"id": 50, "value": "Costa Rica"},
  {"id": 108, "value": "Cote d'Ivoire"},
  {"id": 98, "value": "Croatia"},
  {"id": 52, "value": "Cuba"},
  {"id": 244, "value": "Curaçao"},
  {"id": 55, "value": "Cyprus"},
  {"id": 68, "value": "Czechia"},
  {"id": 56, "value": "Denmark"},
  {"id": 57, "value": "Djibouti"},
  {"id": 58, "value": "Dominica"},
  {"id": 59, "value": "Dominican Republic"},
  {"id": 60, "value": "Ecuador"},
  {"id": 61, "value": "Egypt"},
  {"id": 66, "value": "El Salvador"},
  {"id": 63, "value": "Equatorial Guinea"},
  {"id": 65, "value": "Eritrea"},
  {"id": 64, "value": "Estonia"},
  {"id": 237, "value": "Eswatini"},
  {"id": 67, "value": "Ethiopia"},
  {"id": 72, "value": "Falkland Islands"},
  {"id": 74, "value": "Faroe Islands"},
  {"id": 71, "value": "Fiji"},
  {"id": 70, "value": "Finland"},
  {"id": 76, "value": "France"},
  {"id": 77, "value": "French Antarctic"},
  {"id": 69, "value": "French Guiana"},
  {"id": 75, "value": "French Polynesia"},
  {"id": 79, "value": "Gabon"},
  {"id": 78, "value": "Gambia"},
  {"id": 80, "value": "Georgia"},
  {"id": 86, "value": "Germany"},
  {"id": 81, "value": "Ghana"},
  {"id": 82, "value": "Gibraltar"},
  {"id": 89, "value": "Greece"},
  {"id": 85, "value": "Greenland"},
  {"id": 83, "value": "Grenada"},
  {"id": 87, "value": "Guadeloupe"},
  {"id": 88, "value": "Guam"},
  {"id": 90, "value": "Guatemala"},
  {"id": 84, "value": "Guernsey"},
  {"id": 91, "value": "Guinea"},
  {"id": 175, "value": "Guinea-Bissau"},
  {"id": 92, "value": "Guyana"},
  {"id": 94, "value": "Haiti"},
  {"id": 96, "value": "Heard & McDonald Is"},
  {"id": 232, "value": "Holy See (Vatican City)"},
  {"id": 97, "value": "Honduras"},
  {"id": 95, "value": "Hong Kong (China)"},
  {"id": 99, "value": "Hungary"},
  {"id": 100, "value": "Iceland"},
  {"id": 103, "value": "India"},
  {"id": 101, "value": "Indonesia"},
  {"id": 105, "value": "Iran"},
  {"id": 109, "value": "Iraq"},
  {"id": 62, "value": "Ireland"},
  {"id": 102, "value": "Isle of Man"},
  {"id": 106, "value": "Israel"},
  {"id": 107, "value": "Italy"},
  {"id": 112, "value": "Jamaica"},
  {"id": 110, "value": "Japan"},
  {"id": 111, "value": "Jersey"},
  {"id": 113, "value": "Jordan"},
  {"id": 121, "value": "Kazakhstan"},
  {"id": 114, "value": "Kenya"},
  {"id": 117, "value": "Kiribati"},
  {"id": 118, "value": "Korea, South"},
  {"id": 120, "value": "Kuwait"},
  {"id": 115, "value": "Kyrgyzstan"},
  {"id": 122, "value": "Laos"},
  {"id": 124, "value": "Latvia"},
  {"id": 123, "value": "Lebanon"},
  {"id": 129, "value": "Lesotho"},
  {"id": 126, "value": "Liberia"},
  {"id": 131, "value": "Libya"},
  {"id": 128, "value": "Liechtenstein"},
  {"id": 125, "value": "Lithuania"},
  {"id": 130, "value": "Luxembourg"},
  {"id": 134, "value": "Macau (China)"},
  {"id": 132, "value": "Madagascar"},
  {"id": 139, "value": "Malawi"},
  {"id": 150, "value": "Malaysia"},
  {"id": 148, "value": "Maldives"},
  {"id": 141, "value": "Mali"},
  {"id": 146, "value": "Malta"},
  {"id": 178, "value": "Marshall Islands"},
  {"id": 133, "value": "Martinique"},
  {"id": 145, "value": "Mauritania"},
  {"id": 144, "value": "Mauritius"},
  {"id": 136, "value": "Mayotte"},
  {"id": 149, "value": "Mexico"},
  {"id": 73, "value": "Micronesia"},
  {"id": 135, "value": "Moldova"},
  {"id": 142, "value": "Monaco"},
  {"id": 137, "value": "Mongolia"},
  {"id": 246, "value": "Montenegro"},
  {"id": 138, "value": "Montserrat"},
  {"id": 143, "value": "Morocco"},
  {"id": 151, "value": "Mozambique"},
  {"id": 242, "value": "Myanmar"},
  {"id": 233, "value": "Namibia"},
  {"id": 161, "value": "Nauru"},
  {"id": 160, "value": "Nepal"},
  {"id": 158, "value": "Netherlands"},
  {"id": 152, "value": "New Caledonia"},
  {"id": 165, "value": "New Zealand"},
  {"id": 164, "value": "Nicaragua"},
  {"id": 155, "value": "Niger"},
  {"id": 157, "value": "Nigeria"},
  {"id": 153, "value": "Niue"},
  {"id": 154, "value": "Norfolk Island"},
  {"id": 140, "value": "North Macedonia"},
  {"id": 49, "value": "Northern Mariana Is."},
  {"id": 159, "value": "Norway"},
  {"id": 147, "value": "Oman"},
  {"id": 169, "value": "Pakistan"},
  {"id": 174, "value": "Palau"},
  {"id": 93, "value": "Palestine"},
  {"id": 171, "value": "Panama"},
  {"id": 173, "value": "Papua New Guinea"},
  {"id": 166, "value": "Paraguay"},
  {"id": 168, "value": "Peru"},
  {"id": 180, "value": "Philippines"},
  {"id": 167, "value": "Pitcairn Islands"},
  {"id": 170, "value": "Poland"},
  {"id": 172, "value": "Portugal"},
  {"id": 181, "value": "Puerto Rico"},
  {"id": 176, "value": "Qatar"},
  {"id": 177, "value": "Reunion"},
  {"id": 179, "value": "Romania"},
  {"id": 182, "value": "Russia"},
  {"id": 183, "value": "Rwanda"},
  {"id": 248, "value": "Saint Barthélemy"},
  {"id": 190, "value": "Saint Helena"},
  {"id": 197, "value": "Saint Lucia"},
  {"id": 249, "value": "Saint Martin"},
  {"id": 236, "value": "Samoa"},
  {"id": 193, "value": "San Marino"},
  {"id": 211, "value": "Sao Tome & Principe"},
  {"id": 184, "value": "Saudi Arabia"},
  {"id": 189, "value": "Senegal"},
  {"id": 238, "value": "Serbia"},
  {"id": 187, "value": "Seychelles"},
  {"id": 192, "value": "Sierra Leone"},
  {"id": 194, "value": "Singapore"},
  {"id": 245, "value": "Sint Maarten"},
  {"id": 127, "value": "Slovakia"},
  {"id": 191, "value": "Slovenia"},
  {"id": 29, "value": "Solomon Islands"},
  {"id": 195, "value": "Somalia"},
  {"id": 188, "value": "South Africa"},
  {"id": 201, "value": "South Georgia Island"},
  {"id": 243, "value": "South Sudan"},
  {"id": 196, "value": "Spain"},
  {"id": 39, "value": "Sri Lanka"},
  {"id": 186, "value": "St Kitts & Nevis"},
  {"id": 185, "value": "St Pierre &  Miquelon"},
  {"id": 227, "value": "St Vincent Grenadines"},
  {"id": 198, "value": "Sudan"},
  {"id": 162, "value": "Suriname"},
  {"id": 199, "value": "Svalbard & Jan Mayen"},
  {"id": 200, "value": "Sweden"},
  {"id": 203, "value": "Switzerland"},
  {"id": 202, "value": "Syria"},
  {"id": 216, "value": "Taiwan (China)"},
  {"id": 206, "value": "Tajikistan"},
  {"id": 218, "value": "Tanzania"},
  {"id": 205, "value": "Thailand"},
  {"id": 213, "value": "Timor Leste"},
  {"id": 210, "value": "Togo"},
  {"id": 208, "value": "Tokelau"},
  {"id": 209, "value": "Tonga"},
  {"id": 204, "value": "Trinidad and Tobago"},
  {"id": 212, "value": "Tunisia"},
  {"id": 214, "value": "Turkey"},
  {"id": 217, "value": "Turkmenistan"},
  {"id": 207, "value": "Turks & Caicos Is."},
  {"id": 215, "value": "Tuvalu"},
  {"id": 219, "value": "Uganda"},
  {"id": 222, "value": "Ukraine"},
  {"id": 3, "value": "United Arab Emirates"},
  {"id": 220, "value": "United Kingdom"},
  {"id": 223, "value": "United States"},
  {"id": 225, "value": "Uruguay"},
  {"id": 221, "value": "US Minor Outlying Is"},
  {"id": 226, "value": "Uzbekistan"},
  {"id": 156, "value": "Vanuatu"},
  {"id": 228, "value": "Venezuela"},
  {"id": 230, "value": "Vietnam"},
  {"id": 229, "value": "Virgin Islands (British)"},
  {"id": 231, "value": "Virgin Islands (US)"},
  {"id": 234, "value": "Wallis and Futuna"},
  {"id": 235, "value": "Western Sahara"},
  {"id": 239, "value": "Yemen"},
  {"id": 240, "value": "Zambia"},
  {"id": 241, "value": "Zimbabwe"}
];
